version: '3.1'

services:
  web:
    container_name: web_contact_list
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/code
      - ./host.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/my-site.com.crt:/etc/nginx/my-site.com.crt # SSL certificate
      - ./docker/nginx/my-site.com.key:/etc/nginx/my-site.com.key # SSL Key
    links:
      - php:php
    networks:
      - api_contact_list

  php:
    container_name: php_contact_list
    restart: always
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/code
    depends_on:
      - database
    networks:
      - api_contact_list

  composer:
    container_name: composer_contact_list
    image: composer:latest
#    command: install -vvv
    command: composer install --ignore-platform-reqs # run the installation inside the context container
    volumes:
      - ./:/app
    networks:
      - api_contact_list

  # pulling the database.
  database:
    container_name: database
    restart: always
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - api_contact_list
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker


networks:
  api_contact_list:
    driver: bridge
