<?php

class ContactsTest extends TestCase
{
    protected $id = false,
        $contacts = null;

    protected function setUp (): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->contacts = factory(\App\Models\Contact::class)->make()->create();
        $this->id = $this->contacts->id;
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testGet()
    {
        $this->get('/contacts');

        $this->assertJson($this->response->getContent(), "The get endpoint is working fine.");
    }

//    public function testPost()
//    {
//        $this->post("/contacts", ["contacts" => $this->contacts])
//            ->assertResponseStatus(201);
//    }
//
//    public function testPut()
//    {
//        $this->put("/contacts/{$this->id}", [ "contacts" => $this->contacts])
//            ->assertResponseStatus(200);
//    }
//
//    public function testFind()
//    {
//        $this->get("/contacts/{$this->id}")
//            ->assertResponseStatus(200);
//    }
//
//    public function testDelete()
//    {
//        $this->delete("/contacts/{$this->id}")
//            ->assertResponseStatus(200);
//    }
}
